"""Prove that ONE Dhan login serves every strategy — and that Dhan serves
every Data-API capability the plan pays for.

    python verify.py              # full check (logs in only if no valid token exists)
    python verify.py --no-login   # never log in: fail instead
    python verify.py --no-ws      # skip the three WebSocket probes
    python verify.py --quick      # token + account only; no capability probes, no strategies
    python verify.py --token-file FILE
                                  # probe with SOME OTHER token (e.g. one generated by hand on
                                  # web.dhan.co) instead of the stored one: sections 1-3 only,
                                  # nothing is saved. Delete the file afterwards.

Sections:
  1. the shared package: credentials present, token on disk, decoded offline
  2. Dhan accepts the token (/profile) — token validity, segments, data plan, static IP
  3. the six Data-API capabilities, each asked directly (capabilities.py)
  4. every strategy that imports this package, run in its OWN process the way
     it really runs, lands on the same token file and the same token
  5. none of them triggered a second login

Strategies are discovered by scanning strategy_by_ai/ for files that import
yash_dhan_auth; known ones get a probe that goes through their own client
code, unknown ones are listed so a probe can be added here.

Read-only against Dhan — never places an order.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime

_PKG_DIR = os.path.abspath(os.path.dirname(__file__))
_PARENT = os.path.abspath(os.path.join(_PKG_DIR, ".."))
if _PARENT not in sys.path:
    sys.path.insert(0, _PARENT)

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:                                # noqa: BLE001
    pass

from yash_dhan_auth import (CREDS_FILE, IST, TOKEN_FILE, check_capabilities,  # noqa: E402
                            check_token, market_open_now, rest_headers, token_info)
from yash_dhan_auth.token_manager import API_BASE, _json, _request             # noqa: E402

OK, BAD, UNK = "  [ OK ]", "  [FAIL]", "  [ ?? ]"
_results: list[bool] = []
_unknown = 0


def check(label: str, passed: bool | None, detail: str = "") -> bool:
    global _unknown
    if passed is None:
        _unknown += 1
        print(f"{UNK} {label}" + (f"  — {detail}" if detail else ""))
        return False
    _results.append(bool(passed))
    print(f"{OK if passed else BAD} {label}" + (f"  — {detail}" if detail else ""))
    return bool(passed)


def fingerprint(token: str) -> str:
    """Short, non-secret identifier for a token, safe to print/compare."""
    return hashlib.sha256(token.encode()).hexdigest()[:16]


# ══════════════════════════════════════════════════════════════════════════
# strategies — each probe runs the strategy's OWN client code in a subprocess
# ══════════════════════════════════════════════════════════════════════════
_PROBE = """
import json, os, sys
sys.path.insert(0, {root!r}); sys.path.insert(0, {parent!r}); os.chdir({root!r})
import logging; logging.basicConfig(level=logging.WARNING)
{importer}
from yash_dhan_auth import TOKEN_FILE as tf
print("PROBE " + json.dumps({{"token_file": tf, "client_id": str(cid), "token": tok}}))
"""

# folder -> the lines that obtain (cid, tok) exactly the way the strategy does
KNOWN = {
    "alpha_lab": """
from data.dhan_history import get_client          # candle downloader's own client
c = get_client()
cid, tok = c.dhan_http.client_id, c.dhan_http.access_token
""",
    "hma_vwap": """
from core import market                           # REST auth + the feed's credentials()
cid, tok = market.credentials()
""",
    "premium_harvester": """
from live.dhan_client import Dhan                 # the paper trader's rate-limited wrapper
d = Dhan()
cid, tok = d.client_id, d._token
""",
    "filings_feed": """
from core.book import _dhan_client                # holdings/positions book
c = _dhan_client()
cid, tok = c.dhan_http.client_id, c.dhan_http.access_token
""",
}

_SKIP_DIRS = {".venv", "venv", "__pycache__", ".git", "logs", "node_modules",
              os.path.basename(_PKG_DIR), "yash_kotak_auth"}


def discover_consumers() -> list[str]:
    """Sibling folders whose .py files import yash_dhan_auth."""
    found = []
    for name in sorted(os.listdir(_PARENT)):
        folder = os.path.join(_PARENT, name)
        if name in _SKIP_DIRS or not os.path.isdir(folder):
            continue
        for dirpath, dirnames, filenames in os.walk(folder):
            dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS and not d.startswith(".")]
            for fn in filenames:
                if fn.endswith(".py"):
                    try:
                        with open(os.path.join(dirpath, fn), encoding="utf-8", errors="ignore") as f:
                            if "yash_dhan_auth" in f.read():
                                found.append(name)
                                break
                    except OSError:
                        pass
            if found and found[-1] == name:
                break
    return found


def probe(name: str, importer: str) -> dict | None:
    root = os.path.join(_PARENT, name)
    code = _PROBE.format(root=root, parent=_PARENT, importer=importer)
    try:
        p = subprocess.run([sys.executable, "-c", code], capture_output=True,
                           text=True, cwd=root, timeout=300)
    except subprocess.TimeoutExpired:
        print(f"{BAD} {name}: probe timed out after 300s")
        _results.append(False)
        return None
    for line in reversed(p.stdout.splitlines()):
        if line.startswith("PROBE "):
            return json.loads(line[6:])
    print(f"{BAD} {name}: probe produced no result")
    for t in (p.stderr or p.stdout).strip().splitlines()[-5:]:
        print(f"         {t}")
    _results.append(False)
    return None


# ══════════════════════════════════════════════════════════════════════════
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-login", action="store_true", help="fail instead of performing a login")
    ap.add_argument("--no-ws", action="store_true", help="skip the WebSocket capability probes")
    ap.add_argument("--quick", action="store_true", help="token + account only")
    ap.add_argument("--token-file", metavar="FILE",
                    help="probe with the access token in FILE (first line) instead of the stored one; "
                         "sections 1-3 only, nothing saved")
    args = ap.parse_args()

    if args.token_file:
        return main_other_token(args)

    print("Shared Dhan auth — verification\n")
    print(f"package : {_PKG_DIR}")
    print(f"creds   : {CREDS_FILE}")
    print(f"token   : {TOKEN_FILE}\n")

    print("1) Shared package")
    if not check("credentials file present", os.path.exists(CREDS_FILE)):
        print("\n       Run: python credentials_setup.py")
        return 1
    info = token_info()
    check("token file present and readable", info is not None,
          "" if info else "no token yet — the first strategy to run will log in")
    if info:
        check("token is from today (IST) and not near expiry", info["usable"],
              f"type {info['token_type'] or '?'}, generated {info['generated_at']}, "
              f"expires {info['expires_at']} ({(info['seconds_left'] or 0) // 3600}h left)")

    print("\n2) Dhan accepts the token")
    if args.no_login:
        if not info:
            check("token on disk", False, "--no-login and no token")
            return 1
        saved = json.load(open(TOKEN_FILE))
        cid, tok = saved["client_id"], saved["access_token"]
    else:
        from yash_dhan_auth import LoginDisabled, get_valid_token_with_retry, login_disabled
        if login_disabled():
            print("         YASH_DHAN_AUTH_NO_LOGIN=1: this machine never logs in — using the token on disk")
        try:
            cid, tok = get_valid_token_with_retry()
        except LoginDisabled as e:
            check("usable token on disk", False, str(e))
            return summary()
    status, detail = check_token(cid, tok)
    profile = detail if isinstance(detail, dict) else {}
    check("Dhan accepts the token (/v2/profile)", status == "valid",
          f"client {cid}, token {fingerprint(tok)}" if status == "valid" else f"{status}: {detail}")
    if profile:
        print(f"         token valid till {profile.get('tokenValidity')} | segments {profile.get('activeSegment')}"
              f" | DDPI {profile.get('ddpi')} | MTF {profile.get('mtf')}")
        check("Data API plan active on the account",
              str(profile.get("dataPlan", "")).lower() == "active",
              f"dataPlan {profile.get('dataPlan')}, valid till {profile.get('dataValidity')}")
    try:
        r = _request("GET", f"{API_BASE}/ip/getIP", headers=rest_headers(cid, tok), timeout=15)
        ip = _json(r) if r.status_code == 200 else {}
        check("static IP whitelisted for order APIs", bool(ip.get("ordersAllowed")) if ip else None,
              (f"detected {ip.get('detectedIP')} → {ip.get('ipMatchStatus')} "
               f"(primary {ip.get('primaryIP')}, secondary {ip.get('secondaryIP')})") if ip
              else f"HTTP {r.status_code}: {r.text[:100]}")
    except Exception as e:                       # noqa: BLE001
        check("static IP whitelisted for order APIs", None, str(e)[:120])
    base = fingerprint(tok)

    if args.quick:
        return summary()

    print(f"\n3) Data-API capabilities (market {'OPEN' if market_open_now() else 'closed'} — "
          f"WebSocket silence is inconclusive when closed)")
    if status != "valid":
        print("         skipped — Dhan does not accept the token")
    else:
        for cap in check_capabilities(cid, tok, websockets=not args.no_ws):
            check(f"{cap.name}", cap.ok, f"{cap.endpoint} — {cap.detail}")

    print("\n4) Strategies, each in its own process")
    consumers = discover_consumers()
    if status != "valid":
        print("         skipped — a strategy would try to log in with a token Dhan rejects")
    elif not consumers:
        print("         no sibling folder imports yash_dhan_auth")
    for name in consumers if status == "valid" else []:
        importer = KNOWN.get(name)
        if not importer:
            check(f"{name}", None, "imports the package but has no probe here — add one to KNOWN in verify.py")
            continue
        res = probe(name, importer)
        if not res:
            continue
        same_file = os.path.normcase(res["token_file"]) == os.path.normcase(TOKEN_FILE)
        same_tok = fingerprint(res["token"]) == base
        check(f"{name}: shared token file, same token, same client",
              same_file and same_tok and res["client_id"] == str(cid),
              f"{fingerprint(res['token'])}" + ("" if same_file else f" — DIFFERENT FILE {res['token_file']}"))

    print("\n5) No strategy triggered a second login")
    if os.path.exists(TOKEN_FILE):
        final = json.load(open(TOKEN_FILE))
        check("token on disk unchanged after all strategies ran",
              fingerprint(final["access_token"]) == base, f"{base} (one login serves all)")
    return summary()


def main_other_token(args) -> int:
    """Sections 1-3 with a token handed in by file — the experiment for 'is it
    the token TYPE?': generate one by hand on web.dhan.co (type SELF), put it
    in a file, run this, delete the file. Nothing is written to disk."""
    from yash_dhan_auth import token_claims, token_expiry, token_type
    with open(args.token_file) as f:
        tok = f.readline().strip().strip('"')
    claims = token_claims(tok)
    cid = str(claims.get("dhanClientId") or "")
    print(f"Shared Dhan auth — probing a token from {args.token_file} (nothing will be saved)\n")
    print("1) The token itself (decoded offline)")
    if not check("looks like a Dhan JWT", bool(claims),
                 "" if claims else "no claims — is the whole token on the first line?"):
        return summary()
    exp = token_expiry(tok)
    check("not expired", bool(exp) and exp > datetime.now(IST),
          f"type {token_type(tok) or '?'}, client {cid or '?'}, expires {exp.isoformat() if exp else '?'}")
    extra = {k: v for k, v in claims.items() if k not in ("iss", "iat", "exp", "dhanClientId", "tokenConsumerType")}
    print(f"         other claims: {extra}")

    print("\n2) Dhan accepts the token")
    status, detail = check_token(cid, tok)
    profile = detail if isinstance(detail, dict) else {}
    check("Dhan accepts the token (/v2/profile)", status == "valid",
          f"client {cid}, token {fingerprint(tok)}" if status == "valid" else f"{status}: {detail}")
    if profile:
        check("Data API plan active on the account", str(profile.get("dataPlan", "")).lower() == "active",
              f"dataPlan {profile.get('dataPlan')}, valid till {profile.get('dataValidity')}")

    print(f"\n3) Data-API capabilities (market {'OPEN' if market_open_now() else 'closed'})")
    if status == "valid":
        for cap in check_capabilities(cid, tok, websockets=not args.no_ws):
            check(f"{cap.name}", cap.ok, f"{cap.endpoint} — {cap.detail}")
    print(f"\n         Compare with the stored {token_type(json.load(open(TOKEN_FILE))['access_token']) if os.path.exists(TOKEN_FILE) else 'APP'} "
          f"token: python verify.py --no-login --no-ws")
    return summary()


def summary() -> int:
    failed = _results.count(False)
    print("\n" + "─" * 62)
    extra = f" ({_unknown} inconclusive)" if _unknown else ""
    if failed:
        print(f"{failed} of {len(_results)} checks FAILED{extra}")
        return 1
    print(f"All {len(_results)} checks passed{extra} — one login authenticates every strategy.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
